# jpa Setting
spring:
  jpa:
    hibernate:
#      ddl-auto: create-drop # jpa DB table update
      ddl-auto: update
    generate-ddl: false # db 초기화 설정 끔
    show-sql: true # 사용된 sql 보임
    # h2 설정
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    # test h2db setting
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    username: h2test
#    password: h2test
    # mariaDB Setting
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/shabit
    username: root
    password: 1234

  # Mail Sending
  mail:
    host: smtp.naver.com
    port: 587
    username: dnzma13
    password: guswls6824^*@$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Hibernate loggin
logging:
  level:
    org:
      Hibernate: info

jwt:
  secret: UDVaY0VRREoyaEl2d2JlWXFFN2haOWF3ekRxbFBzTnpscEFFaE5mdDBSZw==

# key
key:
  youtube: AIzaSyCgGyrOibFVCbL9Bvkqt0A8MWEYEZPwwJc
