# jpa Setting
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "135940431465-e82m01dj8rp1ufn8go11e5351052ri2q.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
          naver:
            client-id: "7Ok2n8mRGPoSxzGABJRc"
            client-secret: "QeTRN6VlPc"
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      #      ddl-auto: create-drop # jpa DB table update
      ddl-auto: create-drop
    generate-ddl: false # db 초기화 설정 끔
    show-sql: true # 사용된 sql 보임
    # h2 설정
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    # test h2db setting
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    #    username: h2test
    #    password: h2test
    # mariaDB Setting
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://i8a601.p.ssafy.io:3306/ssafy601
    url: jdbc:mariadb://localhost:3307/ssafy601
    username: ssafy601
    password: ssafy601

  # Mail Sending
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafyezpz
    password: lclsylxuudaclbwc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
#      host: i8a601.p.ssafy.io
      host: localhost
      port: 6379

# S3 setting
cloud:
  aws:
    s3:
      bucket: shabit
    region:
      static: ap-northeast-2 #Asia Pacific -> seoul
    stack:
      auto: false
    credentials:
      instanceProfile: true
      access-key: AKIARYFPHUBQGRUEKLLL
      secret-key: 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

# Hibernate loggin
logging:
  level:
    org:
      Hibernate: info

mail:
  setFrom: ssafyezpz@gmail.com

jwt:
  secret: UDVaY0VRREoyaEl2d2JlWXFFN2haOWF3ekRxbFBzTnpscEFFaE5mdDBSZw==

key:
  youtube: AIzaSyCgGyrOibFVCbL9Bvkqt0A8MWEYEZPwwJc
